### ISSUE TITLE
How to execute post install composer scripts

### ISSUE THREAD

**Issue by davidromani** [servergrove/ansible-symfony2#44]
Hi.

I need to execute ```Incenteev\\ParameterHandler\\ScriptHandler::buildParameters``` interactively. Is this possible?

My deploy config is:

```yaml
---
- name: Deploy project to S6 production server
  hosts: s6
  roles:
    - { role: servergrove.symfony2 }
  vars:
    # custom config
    vhost_name: "<HIDDEN_SECRET>"
    vhost_path: "<HIDDEN_SECRET>"
    # mandatory role config
    symfony_project_root: "{{ vhost_path }}/{{ vhost_name }}"
    symfony_project_composer_path: "{{ vhost_path }}/{{ vhost_name }}/shared/composer.phar"
    symfony_project_repo: "<HIDDEN_SECRET>"
    symfony_project_env: "prod"
    # optional role config
    symfony_project_branch: "master"
    symfony_project_keep_releases: 3
    symfony_project_composer_opts: "--no-dev --optimize-autoloader"
    symfony_project_shared_folders:
      - { name: logs, src: app/logs, path: app/logs }
```
